name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hardcoded password scanner
        run: |
          chmod +x scripts/check-hardcoded-passwords.sh
          ./scripts/check-hardcoded-passwords.sh

  lint:
    needs: secret-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint frontend
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            npm ci || true
            npm run lint || true
          else
            echo "No frontend folder"
          fi

      - name: Lint backend
        run: |
          if [ -d "backend" ]; then
            cd backend
            npm ci || true
            npm run lint || true
          else
            echo "No backend folder"
          fi

  build-and-push-to-ecr:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        run: |
          docker build -t backend-image:latest backend

      - name: Tag & Push backend image
        run: |
          BACKEND_URI=891084863802.dkr.ecr.us-east-1.amazonaws.com/loka/backend:latest
          docker tag backend-image:latest $BACKEND_URI
          docker push $BACKEND_URI

      - name: Build frontend image
        run: |
          docker build -t frontend-image:latest frontend

      - name: Tag & Push frontend image
        run: |
          FRONTEND_URI=891084863802.dkr.ecr.us-east-1.amazonaws.com/loka/frontend:latest
          docker tag frontend-image:latest $FRONTEND_URI
          docker push $FRONTEND_URI
